// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.3
// source: im_user.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ImUserService_VerifyToken_FullMethodName = "/imuser.imUserService/VerifyToken"
)

// ImUserServiceClient is the client API for ImUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImUserServiceClient interface {
	VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error)
}

type imUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImUserServiceClient(cc grpc.ClientConnInterface) ImUserServiceClient {
	return &imUserServiceClient{cc}
}

func (c *imUserServiceClient) VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error) {
	out := new(VerifyTokenResp)
	err := c.cc.Invoke(ctx, ImUserService_VerifyToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImUserServiceServer is the server API for ImUserService service.
// All implementations must embed UnimplementedImUserServiceServer
// for forward compatibility
type ImUserServiceServer interface {
	VerifyToken(context.Context, *VerifyTokenReq) (*VerifyTokenResp, error)
	mustEmbedUnimplementedImUserServiceServer()
}

// UnimplementedImUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImUserServiceServer struct {
}

func (UnimplementedImUserServiceServer) VerifyToken(context.Context, *VerifyTokenReq) (*VerifyTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedImUserServiceServer) mustEmbedUnimplementedImUserServiceServer() {}

// UnsafeImUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImUserServiceServer will
// result in compilation errors.
type UnsafeImUserServiceServer interface {
	mustEmbedUnimplementedImUserServiceServer()
}

func RegisterImUserServiceServer(s grpc.ServiceRegistrar, srv ImUserServiceServer) {
	s.RegisterService(&ImUserService_ServiceDesc, srv)
}

func _ImUserService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImUserServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImUserService_VerifyToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImUserServiceServer).VerifyToken(ctx, req.(*VerifyTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ImUserService_ServiceDesc is the grpc.ServiceDesc for ImUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "imuser.imUserService",
	HandlerType: (*ImUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyToken",
			Handler:    _ImUserService_VerifyToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "im_user.proto",
}
