// Code generated by goctl. DO NOT EDIT.
// Source: im_user.proto

package imuserservice

import (
	"context"

	"goChat/app/usercenter/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	VerifyTokenReq  = pb.VerifyTokenReq
	VerifyTokenResp = pb.VerifyTokenResp

	ImUserService interface {
		VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error)
	}

	defaultImUserService struct {
		cli zrpc.Client
	}
)

func NewImUserService(cli zrpc.Client) ImUserService {
	return &defaultImUserService{
		cli: cli,
	}
}

func (m *defaultImUserService) VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error) {
	client := pb.NewImUserServiceClient(m.cli.Conn())
	return client.VerifyToken(ctx, in, opts...)
}
