// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	imuser "goChat/app/usercenter/cmd/api/internal/handler/imuser"
	"goChat/app/usercenter/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwqAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/white/account/register",
					Handler: imuser.RegisterHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
