// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Token      string `form:"token"`
	SendID     string `form:"sendId"`
	PlatformID string `form:"platformId"`
}

type Response struct {
	Uid     string `json:"uid"`
	ErrMsg  string `json:"errMsg"`
	Success bool `json:"success"`
}
