// Code generated by goctl. DO NOT EDIT.
// Source: im_user.proto

package server

import (
	"context"

	"goChat/app/usercenter/cmd/rpc/internal/logic"
	"goChat/app/usercenter/cmd/rpc/internal/svc"
	"goChat/app/usercenter/cmd/rpc/pb"
)

type ImUserServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedImUserServiceServer
}

func NewImUserServiceServer(svcCtx *svc.ServiceContext) *ImUserServiceServer {
	return &ImUserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ImUserServiceServer) VerifyToken(ctx context.Context, in *pb.VerifyTokenReq) (*pb.VerifyTokenResp, error) {
	l := logic.NewVerifyTokenLogic(ctx, s.svcCtx)
	return l.VerifyToken(in)
}
