// Code generated by goctl. DO NOT EDIT.
// Source: usercenter.proto

package server

import (
	"context"

	"goChat/app/usercenter/cmd/rpc/internal/logic"
	"goChat/app/usercenter/cmd/rpc/internal/svc"
	"goChat/app/usercenter/cmd/rpc/pb"
)

type UsercenterServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsercenterServiceServer
}

func NewUsercenterServiceServer(svcCtx *svc.ServiceContext) *UsercenterServiceServer {
	return &UsercenterServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServiceServer) GeTUserByUsername(ctx context.Context, in *pb.GeTUserByUsernameReq) (*pb.GeTUserResp, error) {
	l := logic.NewGeTUserByUsernameLogic(ctx, s.svcCtx)
	return l.GeTUserByUsername(in)
}

func (s *UsercenterServiceServer) InsertUser(ctx context.Context, in *pb.InsertUserReq) (*pb.InsertUserResp, error) {
	l := logic.NewInsertUserLogic(ctx, s.svcCtx)
	return l.InsertUser(in)
}

func (s *UsercenterServiceServer) LoginById(ctx context.Context, in *pb.LoginByIdReq) (*pb.LoginByIdResp, error) {
	l := logic.NewLoginByIdLogic(ctx, s.svcCtx)
	return l.LoginById(in)
}
