// Code generated by goctl. DO NOT EDIT.
// Source: ws.proto

package server

import (
	"goChat/app/msg/cmd/rpc/internal/logic"
	"goChat/app/msg/cmd/rpc/internal/svc"
	"goChat/app/msg/cmd/rpc/pb"
)

type ExampleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedExampleServer
}

func NewExampleServer(svcCtx *svc.ServiceContext) *ExampleServer {
	return &ExampleServer{
		svcCtx: svcCtx,
	}
}
